version: "3"

services: 
  api:
    container_name: automatic_debit_api
    build: 
      context: ./automatic_debit
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - ./automatic_debit:/app
    ports:
      - "8000:8000"