version: "3"

services: 
  api:
    container_name: automatic_debit_api
    env_file: ./.env
    build: 
      context: ./automatic_debit_api
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    volumes: 
      - ./automatic_debit_api:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
  
  db:
    container_name: api_database
    image: postgres:13-alpine
    env_file: ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
