name: Main workflow (test & lint)
on: push

jobs:
  django-tests:
    name: Run Django tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automatic_debit_api/requirements.txt
          pip install flake8
      - name: Lint the code
        run: |
          flake8 --config ".flake8"
      - name: Run the tests
        run: |
          cd automatic_debit_api
          python3 manage.py test